apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: {{ .Release.Name }}
  namespace: bookinfo-dev
spec:
  rules:
  - host: bookinfo.dev.opsta.net
    http:
      paths:
      - path: /ratings(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 9080