apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.ratings.namaspace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.ratings.port }}
  selector:
    app: {{ .Release.Name }}