---
name: 01 Basic Dcoker Build

env:
  GKE_CLUSTER: iconica  
  GKE_ZONE: asia-southeast1-a	 
  DEPLOYMENT_NAME: ${{ github.event.repository.name }} 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker build & push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ format('unknopu/{0}:latest', env.DEPLOYMENT_NAME) }}
