---
name: 01 Basic Dcoker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: Login 2 Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.evet_name != 'pull_request' }}
          tags: unknopu/allhands22:latest,unknopu/allhands22:01

          cache-from: type=gha
          cache-to: type=gha,mode=max

          platforms: linux/amd64,linux/arm64,linux/arm/v7
